# Generated by Django 5.2.8 on 2025-12-21 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owners',
            old_name='email',
            new_name='owneremail',
        ),
        migrations.RenameField(
            model_name='owners',
            old_name='name',
            new_name='ownername',
        ),
        migrations.RenameField(
            model_name='owners',
            old_name='password',
            new_name='ownerpassword',
        ),
    ]
