# Generated by Django 5.2.8 on 2025-12-28 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_packages'),
    ]

    operations = [
        migrations.CreateModel(
            name='LowestPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('decoration', models.CharField(max_length=3)),
                ('stage_setup', models.CharField(max_length=3)),
                ('sound_system', models.CharField(max_length=3)),
                ('dj', models.CharField(max_length=3)),
                ('catering', models.CharField(max_length=3)),
                ('photography', models.CharField(max_length=3)),
                ('videography', models.CharField(max_length=3)),
                ('games', models.CharField(max_length=3)),
                ('gifts', models.CharField(max_length=3)),
                ('backup_generator', models.CharField(max_length=3)),
                ('security', models.CharField(max_length=3)),
                ('vip_service', models.CharField(max_length=3)),
                ('seating_capacity', models.IntegerField()),
                ('lighting', models.CharField(max_length=3)),
                ('food_type', models.CharField(max_length=20)),
                ('staff_count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.owners')),
            ],
            options={
                'db_table': 'lowest_package',
            },
        ),
        migrations.CreateModel(
            name='MediumPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('decoration', models.CharField(max_length=3)),
                ('stage_setup', models.CharField(max_length=3)),
                ('sound_system', models.CharField(max_length=3)),
                ('dj', models.CharField(max_length=3)),
                ('catering', models.CharField(max_length=3)),
                ('photography', models.CharField(max_length=3)),
                ('videography', models.CharField(max_length=3)),
                ('games', models.CharField(max_length=3)),
                ('gifts', models.CharField(max_length=3)),
                ('backup_generator', models.CharField(max_length=3)),
                ('security', models.CharField(max_length=3)),
                ('vip_service', models.CharField(max_length=3)),
                ('seating_capacity', models.IntegerField()),
                ('lighting', models.CharField(max_length=3)),
                ('food_type', models.CharField(max_length=20)),
                ('staff_count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.owners')),
            ],
            options={
                'db_table': 'medium_package',
            },
        ),
        migrations.CreateModel(
            name='PremiumPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=50)),
                ('decoration', models.CharField(max_length=3)),
                ('stage_setup', models.CharField(max_length=3)),
                ('sound_system', models.CharField(max_length=3)),
                ('dj', models.CharField(max_length=3)),
                ('catering', models.CharField(max_length=3)),
                ('photography', models.CharField(max_length=3)),
                ('videography', models.CharField(max_length=3)),
                ('games', models.CharField(max_length=3)),
                ('gifts', models.CharField(max_length=3)),
                ('backup_generator', models.CharField(max_length=3)),
                ('security', models.CharField(max_length=3)),
                ('vip_service', models.CharField(max_length=3)),
                ('seating_capacity', models.IntegerField()),
                ('lighting', models.CharField(max_length=3)),
                ('food_type', models.CharField(max_length=20)),
                ('staff_count', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.owners')),
            ],
            options={
                'db_table': 'premium_table',
            },
        ),
    ]
