# Generated by Django 5.2.8 on 2025-12-28 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_lowestpackage_mediumpackage_premiumpackage'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='premiumpackage',
            table='premium_package',
        ),
    ]
