# Generated by Django 5.2.8 on 2025-12-29 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lowestpackage_package_mediumpackage_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowestpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='mediumpackage',
            name='package',
        ),
        migrations.RemoveField(
            model_name='premiumpackage',
            name='package',
        ),
    ]
