# Generated by Django 5.2.8 on 2025-12-29 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_lowestpackage_package_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lowestpackage',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.packages'),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.packages'),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.packages'),
        ),
    ]
