# Generated by Django 5.2.8 on 2026-01-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lowestpackage_package_mediumpackage_package_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lowestpackage',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='lowestpackage',
            name='lighting',
        ),
        migrations.RemoveField(
            model_name='lowestpackage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='lowestpackage',
            name='sound_system',
        ),
        migrations.RemoveField(
            model_name='lowestpackage',
            name='staff_count',
        ),
        migrations.RemoveField(
            model_name='lowestpackage',
            name='stage_setup',
        ),
        migrations.RemoveField(
            model_name='mediumpackage',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='mediumpackage',
            name='lighting',
        ),
        migrations.RemoveField(
            model_name='mediumpackage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mediumpackage',
            name='sound_system',
        ),
        migrations.RemoveField(
            model_name='mediumpackage',
            name='staff_count',
        ),
        migrations.RemoveField(
            model_name='mediumpackage',
            name='stage_setup',
        ),
        migrations.RemoveField(
            model_name='premiumpackage',
            name='food_type',
        ),
        migrations.RemoveField(
            model_name='premiumpackage',
            name='lighting',
        ),
        migrations.RemoveField(
            model_name='premiumpackage',
            name='price',
        ),
        migrations.RemoveField(
            model_name='premiumpackage',
            name='sound_system',
        ),
        migrations.RemoveField(
            model_name='premiumpackage',
            name='staff_count',
        ),
        migrations.RemoveField(
            model_name='premiumpackage',
            name='stage_setup',
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='backup_generator_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='catering_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='decoration_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='dj_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='games_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='gifts_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='hall_ac_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='hall_non_ac_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='photography_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='security_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='videography_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='lowestpackage',
            name='vip_service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='backup_generator_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='catering_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='decoration_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='dj_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='games_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='gifts_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='hall_ac_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='hall_non_ac_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='photography_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='security_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='videography_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='mediumpackage',
            name='vip_service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='backup_generator_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='catering_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='decoration_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='dj_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='games_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='gifts_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='hall_ac_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='hall_non_ac_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='photography_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='security_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='videography_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='premiumpackage',
            name='vip_service_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='backup_generator',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='catering',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='decoration',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='dj',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='games',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='gifts',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='photography',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='seating_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='security',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='videography',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='lowestpackage',
            name='vip_service',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='backup_generator',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='catering',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='decoration',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='dj',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='games',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='gifts',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='photography',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='seating_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='security',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='videography',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='mediumpackage',
            name='vip_service',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='backup_generator',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='catering',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='decoration',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='dj',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='games',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='gifts',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='photography',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='seating_capacity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='security',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='videography',
            field=models.CharField(default='no', max_length=3),
        ),
        migrations.AlterField(
            model_name='premiumpackage',
            name='vip_service',
            field=models.CharField(default='no', max_length=3),
        ),
    ]
